name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Access repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
          cache: "npm"
          cache-dependency-path: |
            ui/package-lock.json
            client/package-lock.json
            package-lock.json

      - name: Install ui dependencies
        working-directory: ui
        run: npm ci --ignore-scripts

      - name: Install root dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests
        run: npm run test
